# Generated by Django 4.0.4 on 2022-04-16 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='donationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NGO_id', models.CharField(blank=True, max_length=10)),
                ('Medicine_list', models.CharField(blank=True, max_length=11)),
                ('Delivery_type', models.CharField(blank=True, max_length=11)),
                ('Pick_Up_address', models.CharField(blank=True, max_length=150)),
                ('Acceptance_Status', models.BooleanField(default=False)),
                ('Pick_Up_date', models.DateField()),
                ('Pick_Up_time', models.TimeField()),
                ('Delivery_status', models.CharField(default='pending', max_length=20)),
                ('Donor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
