# Generated by Django 4.0.4 on 2022-04-23 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationRequestSystem', '0002_remove_donationrequest_donor_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donationrequest',
            name='Medicine_list',
        ),
    ]
