# Generated by Django 4.0.4 on 2022-04-16 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_fullname_customuser_identity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='testtable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testfiedl1', models.CharField(blank=True, max_length=10)),
                ('testfiedl2', models.CharField(blank=True, max_length=10)),
            ],
        ),
    ]
