# Generated by Django 4.0.4 on 2022-04-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_fullname_customuser_identity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
