# Generated by Django 4.0.4 on 2022-04-24 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_lat_customuser_lon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='lon',
        ),
    ]
