# Generated by Django 4.2.30 on 2026-07-12 20:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_MedicineListInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=100)),
                ('DosageAmount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PillsLeft', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ExpiryDateImage', models.ImageField(upload_to='medicine_images')),
                ('Donor_id', models.BigIntegerField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='NGO_MedicineListInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=100)),
                ('DosageAmount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('MedicinePriority', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)])),
                ('AmountRequired', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('NGO_id', models.BigIntegerField(db_index=True)),
            ],
        ),
    ]
