global:
  docker_user: warrior47

# TODO: Move secrets to AWS Secrets Manager
mysql:
  root_password: rootpassword   # TODO: Move to external secret store
  database: medicine_donation
  user: admin
  password: password123         # TODO: Move to external secret store

apps:
  django_app:
    name: django-app
    replicas: 2
    maxSurge: 1
    maxUnavailable: 10%
    imageVersion: latest
    containerPort: 8000
    servicePort: 80
    serviceType: NodePort
    healthCheckUrl: /health
    liveness_periodSeconds: 10
    liveness_timeoutSeconds: 5
    liveness_failureThreshold: 3
    readiness_periodSeconds: 5
    readiness_timeoutSeconds: 5
    readiness_failureThreshold: 3
    use_pvc: true
    pvc_name: static-images
    access_mode: ReadWriteOnce
    storage_size: 500Mi
    mount_path: /app/static/img/medicine_images

configmaps:
  django-app-config:
    DB_NAME: "medicine_donation"
    DB_USER: "admin"
    DB_HOST: "mysql.db.svc.cluster.local"
    DB_PORT: "3306"

secrets:
  django-app-secrets:
    DB_PASSWORD: cGFzc3dvcmQxMjM=  # TODO: Move to external secret store