apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  DB_NAME: "medicine_donation"
  DB_USER: "admin"
  DB_HOST: "mysql-service"
  DB_PORT: "3306"

---
apiVersion: v1
kind: Secret
metadata:
  name: django-secrets
type: Opaque
data:
  DB_PASSWORD: cGFzc3dvcmQxMjM=
  SECRET_KEY: eW91ci1zZWNyZXQta2V5