---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django-app
  labels:
    app: django-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django-app
  template:
    metadata:
      labels:
        app: django-app
    spec:
      containers:
      - name: django-app
        image: warrior47/django-app:latest
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: sqlite3
          mountPath: "/app/database"
      volumes:
      - name: sqlite3
        persistentVolumeClaim:
          claimName: sqlite3-pvc
