---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sqlite3-sc
provisioner: hostpath.csi.k8s.io
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: sqlite3-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sqlite3-sc
  resources:
    requests:
      storage: 500Mi