# Generated by Django 4.2.30 on 2026-07-12 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='donationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Donor_id', models.BigIntegerField(db_index=True)),
                ('Donor_name', models.CharField(blank=True, max_length=100)),
                ('Donor_phone', models.CharField(blank=True, max_length=11)),
                ('NGO_id', models.BigIntegerField(db_index=True)),
                ('NGO_name', models.CharField(blank=True, max_length=100)),
                ('Delivery_type', models.CharField(blank=True, max_length=11)),
                ('Pick_Up_address', models.CharField(blank=True, max_length=150)),
                ('Acceptance_Status', models.BooleanField(default=False)),
                ('Pick_Up_date', models.DateField(blank=True, default=None, null=True)),
                ('Pick_Up_time', models.TimeField(blank=True, default=None, null=True)),
                ('Delivery_status', models.CharField(default='pending', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='donatedMedicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(blank=True, max_length=100)),
                ('dosage_amount', models.IntegerField()),
                ('number_of_pills', models.IntegerField()),
                ('donation_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DonationRequestSystem.donationrequest')),
            ],
        ),
    ]
