# Generated by Django 4.0.4 on 2022-04-15 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationSystem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ngo_medicinelistinfo',
            name='AmountRequired',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ngo_medicinelistinfo',
            name='DosageAmount',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ngo_medicinelistinfo',
            name='MedicinePriority',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(3)]),
        ),
    ]
