# Generated by Django 4.0.4 on 2022-04-21 09:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('DonationSystem', '0003_rename_ngo_id_ngo_medicinelistinfo_ngo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_MedicineListInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MedicineName', models.CharField(max_length=100)),
                ('DosageAmount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('PillsLeft', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('ExpiryDateImage', models.ImageField(upload_to='medicine_images')),
                ('Donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
