# Generated by Django 4.0.4 on 2022-04-23 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationRequestSystem', '0003_remove_donationrequest_medicine_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='Pick_Up_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='Pick_Up_time',
            field=models.TimeField(blank=True),
        ),
    ]
