# Generated by Django 4.0.4 on 2022-04-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DonationRequestSystem', '0004_alter_donationrequest_pick_up_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationrequest',
            name='Pick_Up_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donationrequest',
            name='Pick_Up_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
