# Generated by Django 4.0.4 on 2022-04-16 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DonationSystem', '0002_alter_ngo_medicinelistinfo_amountrequired_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ngo_medicinelistinfo',
            old_name='Ngo_Id',
            new_name='NGO',
        ),
    ]
